local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/medias/img"
public_folder: "/assets/medias/img"

collections:
  - name: "paintings"
    label: "Peintures"
    label_singular: "Peinture"
    folder: "src/paintings"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    summary: "{{title}} - {{date}}"
    sortable_fields: ["title", "date", "type", "sold"]
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, picker_utc: true }
      - label: "Dimensions"
        name: "dimensions"
        widget: "object"
        collapsed: false
        fields:
          - { label: "Largeur (cm)", name: "x", widget: "number", value_type: "int" }
          - { label: "Hauteur (cm)", name: "y", widget: "number", value_type: "int" }
      - { label: "Technique", name: "type", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Vendu", name: "sold", widget: "boolean", default: false }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: false }

  - name: "sculptures"
    label: "Sculptures"
    label_singular: "Sculpture"
    folder: "src/sculptures"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    summary: "{{title}} - {{date}}"
    sortable_fields: ["title", "date", "type", "sold"]
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, picker_utc: true }
      - label: "Dimensions"
        name: "dimensions"
        widget: "object"
        collapsed: false
        fields:
          - { label: "Largeur (cm)", name: "x", widget: "number", value_type: "int" }
          - { label: "Hauteur (cm)", name: "y", widget: "number", value_type: "int" }
      - { label: "Technique", name: "type", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Vendu", name: "sold", widget: "boolean", default: false }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: false }

  - name: "calendar"
    label: "Calendrier"
    label_singular: "Événement"
    folder: "src/calendar"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    summary: "{{title}} - {{startDate}}"
    sortable_fields: ["title", "startDate", "endDate", "place", "order"]
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de début", name: "startDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, picker_utc: true, required: false }
      - { label: "Date de fin", name: "endDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, picker_utc: true, required: false }
      - { label: "Lieu", name: "place", widget: "string", required: false }
      - { label: "Note", name: "note", widget: "string", required: false }
      - { label: "Ordre", name: "order", widget: "number", value_type: "int", required: false }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: false }
